# Generated by Django 3.1.2 on 2020-10-06 01:27

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, editable=False),
        ),
    ]
